Für dieses Projekt verwenden wir die European Soccer Database, eine relationale Datenbank. enthält Daten zum über 25.000 spiele 3 und 13 und 10000 Spieler in Europa zwischen 2008 und 2016

In [2]:
%load_ext sql
%sql sqlite://

In [3]:
%sql sqlite://///home/hamid/python/sql/euro_soccer.sqlite

In [4]:
%%sql
SELECT 
    name
FROM 
    sqlite_master 
WHERE 
    type ='table' AND 
    name NOT LIKE 'sqlite_%';

   sqlite://
 * sqlite://///home/hamid/python/sql/euro_soccer.sqlite
Done.

[('Player_Attributes',),
 ('Player',),
 ('Match',),
 ('League',),
 ('Country',),
 ('Team',),
 ('Team_Attributes',)]

die Daten sind aus 7 tabellen enthalten

In [32]:
%%sql 
Drop VIEW League_s;
CREATE VIEW League_s AS
select * from  League limit 1000000;

   sqlite://
 * sqlite://///home/hamid/python/sql/euro_soccer.sqlite
Done.
Done.

[]

In [19]:
 %sql select * from  League_s limit 10;

   sqlite://
 * sqlite://///home/hamid/python/sql/euro_soccer.sqlite
Done.

[(1, 1, 'Belgium Jupiler League'),
 (1729, 1729, 'England Premier League'),
 (4769, 4769, 'France Ligue 1'),
 (7809, 7809, 'Germany 1. Bundesliga'),
 (10257, 10257, 'Italy Serie A'),
 (13274, 13274, 'Netherlands Eredivisie'),
 (15722, 15722, 'Poland Ekstraklasa'),
 (17642, 17642, 'Portugal Liga ZON Sagres'),
 (19694, 19694, 'Scotland Premier League'),
 (21518, 21518, 'Spain LIGA BBVA')]

In [33]:
%%sql 
Drop VIEW Match_s;
CREATE VIEW Match_s AS
select * from  Match limit 1000000;

   sqlite://
 * sqlite://///home/hamid/python/sql/euro_soccer.sqlite
Done.
Done.

[]

In [24]:
%sql select * from  Match_s limit 10;

   sqlite://
 * sqlite://///home/hamid/python/sql/euro_soccer.sqlite
Done.

[(1, 1, 1, '2008/2009', 1, '2008-08-17 00:00:00', 492473, 9987, 9993, 1, 1, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, 1.73, 3.4, 5, 1.75, 3.35, 4.2, 1.85, 3.2, 3.5, 1.8, 3.3, 3.75, None, None, None, 1.7, 3.3, 4.33, 1.9, 3.3, 4, 1.65, 3.4, 4.5, 1.78, 3.25, 4, 1.73, 3.4, 4.2),
 (2, 1, 1, '2008/2009', 1, '2008-08-16 00:00:00', 492474, 10000, 9994, 0, 0, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, 1.95, 3.2, 3.6, 1.8, 3.3, 3.95, 1.9, 3.2, 3.5, 1.9, 3.2, 3.5, None, None, None, 1.83, 3.3, 3.6, 1.95, 3.3, 3.8, 2, 3.25, 3.25, 1.85, 3.25, 3.75, 1.91, 3.25, 3.6),
 (3, 1, 1, '2008/2009', 1, '2008-08-16 00:00:00', 492475, 9984, 8635, 0, 3, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, 2.38, 3.3, 2.75, 2.4, 3.3, 2.55, 2.6, 3.1, 2.3, 2.5, 3.2, 2.5, None, None, None, 2.5, 3.25, 2.4, 2.63, 3.3, 2.5, 2.35, 3.25, 2.65, 2.5, 3.2, 2.5, 2.3, 3.2, 2.75),
 (4, 1, 1, '2008/2009', 1, '2008-08-17 00:00:00', 492476, 9991, 9998, 5, 0, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, 1.44, 3.75, 7.5, 1.4, 4, 6.8, 1.4, 3.9, 6, 1.44, 3.6, 6.5, None, None, None, 1.44, 3.75, 6, 1.44, 4, 7.5, 1.45, 3.75, 6.5, 1.5, 3.75, 5.5, 1.44, 3.75, 6.5),
 (5, 1, 1, '2008/2009', 1, '2008-08-16 00:00:00', 492477, 7947, 9985, 1, 3, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, 5, 3.5, 1.65, 5, 3.5, 1.6, 4, 3.3, 1.7, 4, 3.4, 1.72, None, None, None, 4.2, 3.4, 1.7, 4.5, 3.5, 1.73, 4.5, 3.4, 1.65, 4.5, 3.5, 1.65, 4.75, 3.3, 1.67),
 (6, 1, 1, '2008/2009', 1, '2008-09-24 00:00:00', 492478, 8203, 8342, 1, 1, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, 4.75, 3.4, 1.67, 4.85, 3.4, 1.65, 3.7, 3.2, 1.8, 5, 3.25, 1.62, None, None, None, 4.2, 3.4, 1.7, 5.5, 3.75, 1.67, 4.35, 3.4, 1.7, 4.5, 3.4, 1.7, None, None, None),
 (7, 1, 1, '2008/2009', 1, '2008-08-16 00:00:00', 492479, 9999, 8571, 2, 2, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, 2.1, 3.2, 3.3, 2.05, 3.25, 3.15, 1.85, 3.2, 3.5, 1.83, 3.3, 3.6, None, None, None, 1.83, 3.3, 3.6, 1.91, 3.4, 3.6, 2.1, 3.25, 3, 1.85, 3.25, 3.75, 2.1, 3.25, 3.1),
 (8, 1, 1, '2008/2009', 1, '2008-08-16 00:00:00', 492480, 4049, 9996, 1, 2, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, 3.2, 3.4, 2.2, 2.55, 3.3, 2.4, 2.4, 3.2, 2.4, 2.5, 3.2, 2.5, None, None, None, 2.7, 3.25, 2.25, 2.6, 3.4, 2.4, 2.8, 3.25, 2.25, 2.8, 3.2, 2.25, 2.88, 3.25, 2.2),
 (9, 1, 1, '2008/2009', 1, '2008-08-16 00:00:00', 492481, 10001, 9986, 1, 0, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, 2.25, 3.25, 2.88, 2.3, 3.25, 2.7, 2.1, 3.1, 3, 2.25, 3.2, 2.75, None, None, None, 2.2, 3.25, 2.75, 2.2, 3.3, 3.1, 2.25, 3.25, 2.8, 2.2, 3.3, 2.8, 2.25, 3.2, 2.8),
 (10, 1, 1, '2008/2009', 10, '2008-11-01 00:00:00', 492564, 8342, 8571, 4, 1, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, 1.3, 5.25, 9.5, 1.25, 5, 10, 1.3, 4.2, 8, 1.25, 4.5, 10, None, None, None, 1.35, 4.2, 7, 1.27, 5, 10, 1.3, 4.35, 8.5, 1.25, 5, 10, 1.29, 4.5, 9)]

# Die Abfrage die sich ihr sehen gibt es ihnen die Anzahl der Spieler an die in jede der 11 in der Tabelle Liga aufgeführten liegen gespielt wurden

In [34]:
%%sql
SELECT
    l.name AS league, COUNT(m.country_id) AS total_game
FROM league_s AS l
LEFT JOIN match_s AS m
ON l.country_id = m.country_id
GROUP BY l.name;

   sqlite://
 * sqlite://///home/hamid/python/sql/euro_soccer.sqlite
Done.

[('Belgium Jupiler League', 1728),
 ('England Premier League', 3040),
 ('France Ligue 1', 3040),
 ('Germany 1. Bundesliga', 2448),
 ('Italy Serie A', 3017),
 ('Netherlands Eredivisie', 2448),
 ('Poland Ekstraklasa', 1920),
 ('Portugal Liga ZON Sagres', 2052),
 ('Scotland Premier League', 1824),
 ('Spain LIGA BBVA', 3040),
 ('Switzerland Super League', 1422)]

In [7]:
%%sql
DROP VIEW matches_germany; 
CREATE VIEW matches_germany AS
SELECT m.id, m.country_id, m.season, m.stage, m.date, m.home_team_api_id, m.away_team_api_id, m.home_team_goal, m.away_team_goal
FROM Match as m JOIN Country ON m.country_id = Country.id WHERE name = 'Germany';

   sqlite://
 * sqlite://///home/hamid/python/sql/euro_soccer.sqlite
Done.
Done.

[]

In [95]:
%sql select * from  matches_germany;

   sqlite://
 * sqlite://///home/hamid/python/sql/euro_soccer.sqlite
   sqlite:////home/hamid/python/sql/dataset.sqlite
Done.

[(7809, 7809, '2008/2009', 1, '2008-08-15 00:00:00', 9823, 9790, 2, 2),
 (7810, 7809, '2008/2009', 1, '2008-08-16 00:00:00', 8178, 9789, 2, 3),
 (7811, 7809, '2008/2009', 1, '2008-08-16 00:00:00', 10189, 9904, 3, 0),
 (7812, 7809, '2008/2009', 1, '2008-08-16 00:00:00', 8721, 8722, 2, 1),
 (7813, 7809, '2008/2009', 1, '2008-08-17 00:00:00', 9810, 8177, 0, 2),
 (7814, 7809, '2008/2009', 1, '2008-08-16 00:00:00', 9912, 8697, 2, 2),
 (7815, 7809, '2008/2009', 1, '2008-08-16 00:00:00', 8398, 8226, 0, 3),
 (7816, 7809, '2008/2009', 1, '2008-08-17 00:00:00', 9788, 10269, 1, 3),
 (7817, 7809, '2008/2009', 1, '2008-08-16 00:00:00', 8295, 9911, 1, 0),
 (7818, 7809, '2008/2009', 10, '2008-10-29 00:00:00', 9790, 10269, 2, 0),
 (7819, 7809, '2008/2009', 10, '2008-10-28 00:00:00', 8697, 8178, 0, 2),
 (7820, 7809, '2008/2009', 10, '2008-10-29 00:00:00', 8177, 9904, 3, 0),
 (7821, 7809, '2008/2009', 10, '2008-10-28 00:00:00', 8721, 9788, 3, 0),
 (7822, 7809, '2008/2009', 10, '2008-10-29 00:00:00', 9810, 9823, 1, 2),
 (7823, 7809, '2008/2009', 10, '2008-10-28 00:00:00', 9912, 8398, 1, 1),
 (7824, 7809, '2008/2009', 10, '2008-10-29 00:00:00', 8722, 9789, 0, 1),
 (7825, 7809, '2008/2009', 10, '2008-10-29 00:00:00', 9911, 8226, 1, 3),
 (7826, 7809, '2008/2009', 10, '2008-10-28 00:00:00', 8295, 10189, 0, 3),
 (7827, 7809, '2008/2009', 11, '2008-11-01 00:00:00', 9823, 9912, 3, 1),
 (7828, 7809, '2008/2009', 11, '2008-10-31 00:00:00', 8178, 8721, 2, 0),
 (7829, 7809, '2008/2009', 11, '2008-11-02 00:00:00', 9789, 9911, 1, 1),
 (7830, 7809, '2008/2009', 11, '2008-11-01 00:00:00', 10269, 8722, 1, 3),
 (7831, 7809, '2008/2009', 11, '2008-11-01 00:00:00', 8697, 8177, 5, 1),
 (7832, 7809, '2008/2009', 11, '2008-11-01 00:00:00', 8398, 10189, 0, 2),
 (7833, 7809, '2008/2009', 11, '2008-11-01 00:00:00', 9904, 9790, 3, 0),
 (7834, 7809, '2008/2009', 11, '2008-11-02 00:00:00', 9788, 9810, 1, 2),
 (7835, 7809, '2008/2009', 11, '2008-11-01 00:00:00', 8226, 8295, 4, 1),
 (7836, 7809, '2008/2009', 12, '2008-11-08 00:00:00', 9790, 9789, 2, 1),
 (7837, 7809, '2008/2009', 12, '2008-11-09 00:00:00', 8177, 8226, 1, 0),
 (7838, 7809, '2008/2009', 12, '2008-11-09 00:00:00', 10189, 9823, 1, 2),
 (7839, 7809, '2008/2009', 12, '2008-11-08 00:00:00', 8721, 8398, 3, 0),
 (7840, 7809, '2008/2009', 12, '2008-11-09 00:00:00', 9810, 10269, 2, 2),
 (7841, 7809, '2008/2009', 12, '2008-11-08 00:00:00', 9912, 9788, 0, 2),
 (7842, 7809, '2008/2009', 12, '2008-11-07 00:00:00', 8722, 9904, 2, 1),
 (7843, 7809, '2008/2009', 12, '2008-11-08 00:00:00', 9911, 8697, 0, 0),
 (7844, 7809, '2008/2009', 12, '2008-11-08 00:00:00', 8295, 8178, 3, 3),
 (7845, 7809, '2008/2009', 13, '2008-11-15 00:00:00', 8178, 10189, 2, 1),
 (7846, 7809, '2008/2009', 13, '2008-11-15 00:00:00', 9789, 9810, 4, 0),
 (7847, 7809, '2008/2009', 13, '2008-11-15 00:00:00', 10269, 9912, 0, 0),
 (7848, 7809, '2008/2009', 13, '2008-11-16 00:00:00', 8697, 8722, 3, 1),
 (7849, 7809, '2008/2009', 13, '2008-11-15 00:00:00', 8177, 9790, 2, 1),
 (7850, 7809, '2008/2009', 13, '2008-11-15 00:00:00', 8398, 8295, 1, 0),
 (7851, 7809, '2008/2009', 13, '2008-11-14 00:00:00', 9904, 9911, 1, 1),
 (7852, 7809, '2008/2009', 13, '2008-11-15 00:00:00', 9788, 9823, 2, 2),
 (7853, 7809, '2008/2009', 13, '2008-11-15 00:00:00', 8226, 8721, 3, 2),
 (7854, 7809, '2008/2009', 14, '2008-11-22 00:00:00', 9823, 8398, 4, 1),
 (7855, 7809, '2008/2009', 14, '2008-11-23 00:00:00', 9790, 8697, 2, 1),
 (7856, 7809, '2008/2009', 14, '2008-11-22 00:00:00', 10189, 9788, 3, 1),
 (7857, 7809, '2008/2009', 14, '2008-11-22 00:00:00', 8721, 10269, 4, 1),
 (7858, 7809, '2008/2009', 14, '2008-11-22 00:00:00', 9810, 9904, 4, 0),
 (7859, 7809, '2008/2009', 14, '2008-11-22 00:00:00', 9912, 8178, 2, 1),
 (7860, 7809, '2008/2009', 14, '2008-11-22 00:00:00', 8722, 8226, 1, 3),
 (7861, 7809, '2008/2009', 14, '2008-11-22 00:00:00', 9911, 8177, 2, 3),
 (7862, 7809, '2008/2009', 14, '2008-11-21 00:00:00', 8295, 9789, 0, 1),
 (7863, 7809, '2008/2009', 15, '2008-11-29 00:00:00', 8178, 9823, 0, 2),
 (7864, 7809, '2008/2009', 15, '2008-11-30 00:00:00', 9789, 8721, 0, 0),
 (7865, 7809, '2008/2009', 15, '2008-11-30 00:00:00', 10269, 10189, 2, 0),
 (7866, 7809, '2008/2009', 15, '2008-11-29 00:00:00', 8697, 9810, 5, 0),
 (7867, 7809, '2008/2009', 15, '2008-11-28 00:00:00', 8177, 8722, 2, 1),
 (7868, 7809, '2008/2009', 15, '2008-11-30 00:00:00', 9911, 9790, 1, 1),
 (7869, 7809, '2008/2009', 15, '2008-11-29 00:00:00', 9904, 8295, 3, 2),
 (7870, 7809, '2008/2009', 15, '2008-11-29 00:00:00', 9788, 8398, 1, 3),
 (7871, 7809, '2008/2009', 15, '2008-11-29 00:00:00', 8226, 9912, 3, 0),
 (7872, 7809, '2008/2009', 16, '2008-12-05 00:00:00', 9823, 8226, 2, 1),
 (7873, 7809, '2008/2009', 16, '2008-12-06 00:00:00', 10189, 8177, 1, 0),
 (7874, 7809, '2008/2009', 16, '2008-12-07 00:00:00', 8721, 9904, 2, 1),
 (7875, 7809, '2008/2009', 16, '2008-12-06 00:00:00', 9810, 9911, 4, 0),
 (7876, 7809, '2008/2009', 16, '2008-12-06 00:00:00', 9912, 9789, 0, 0),
 (7877, 7809, '2008/2009', 16, '2008-12-07 00:00:00', 8722, 9790, 1, 2),
 (7878, 7809, '2008/2009', 16, '2008-12-06 00:00:00', 8398, 10269, 0, 3),
 (7879, 7809, '2008/2009', 16, '2008-12-06 00:00:00', 9788, 8178, 1, 3),
 (7880, 7809, '2008/2009', 16, '2008-12-06 00:00:00', 8295, 8697, 1, 0),
 (7881, 7809, '2008/2009', 17, '2008-12-13 00:00:00', 8178, 8398, 1, 1),
 (7882, 7809, '2008/2009', 17, '2008-12-13 00:00:00', 9790, 9810, 1, 0),
 (7883, 7809, '2008/2009', 17, '2008-12-12 00:00:00', 9789, 9788, 2, 1),
 (7884, 7809, '2008/2009', 17, '2008-12-13 00:00:00', 10269, 9823, 2, 2),
 (7885, 7809, '2008/2009', 17, '2008-12-13 00:00:00', 8697, 8721, 2, 1),
 (7886, 7809, '2008/2009', 17, '2008-12-13 00:00:00', 8177, 8295, 4, 0),
 (7887, 7809, '2008/2009', 17, '2008-12-13 00:00:00', 9911, 8722, 1, 2),
 (7888, 7809, '2008/2009', 17, '2008-12-13 00:00:00', 9904, 9912, 1, 1),
 (7889, 7809, '2008/2009', 17, '2008-12-14 00:00:00', 8226, 10189, 1, 1),
 (7890, 7809, '2008/2009', 18, '2009-01-30 00:00:00', 9790, 9823, 1, 0),
 (7891, 7809, '2008/2009', 18, '2009-01-31 00:00:00', 9789, 8178, 1, 1),
 (7892, 7809, '2008/2009', 18, '2009-01-31 00:00:00', 10269, 9788, 2, 0),
 (7893, 7809, '2008/2009', 18, '2009-02-01 00:00:00', 8697, 9912, 1, 2),
 (7894, 7809, '2008/2009', 18, '2009-01-31 00:00:00', 8177, 9810, 2, 1),
 (7895, 7809, '2008/2009', 18, '2009-01-31 00:00:00', 8722, 8721, 1, 1),
 (7896, 7809, '2008/2009', 18, '2009-02-01 00:00:00', 9911, 8295, 2, 0),
 (7897, 7809, '2008/2009', 18, '2009-01-31 00:00:00', 9904, 10189, 1, 0),
 (7898, 7809, '2008/2009', 18, '2009-01-31 00:00:00', 8226, 8398, 2, 0),
 (7899, 7809, '2008/2009', 19, '2009-02-08 00:00:00', 9823, 9789, 3, 1),
 (7900, 7809, '2008/2009', 19, '2009-02-07 00:00:00', 8178, 10269, 2, 4),
 (7901, 7809, '2008/2009', 19, '2009-02-07 00:00:00', 10189, 8697, 1, 0),
 (7902, 7809, '2008/2009', 19, '2009-02-07 00:00:00', 8721, 9911, 2, 0),
 (7903, 7809, '2008/2009', 19, '2009-02-07 00:00:00', 9810, 8722, 2, 2),
 (7904, 7809, '2008/2009', 19, '2009-02-06 00:00:00', 9912, 8177, 1, 1),
 (7905, 7809, '2008/2009', 19, '2009-02-08 00:00:00', 8398, 9904, 3, 1),
 (7906, 7809, '2008/2009', 19, '2009-02-07 00:00:00', 9788, 8226, 1, 1),
 (7907, 7809, '2008/2009', 19, '2009-02-07 00:00:00', 8295, 9790, 3, 2),
 (7908, 7809, '2008/2009', 2, '2008-08-23 00:00:00', 9790, 8295, 2, 1),
 (7909, 7809, '2008/2009', 2, '2008-08-23 00:00:00', 9789, 9823, 1, 1),
 (7910, 7809, '2008/2009', 2, '2008-08-23 00:00:00', 10269, 8178, 0, 2),
 (7911, 7809, '2008/2009', 2, '2008-08-23 00:00:00', 8697, 10189, 1, 1),
 (7912, 7809, '2008/2009', 2, '2008-08-23 00:00:00', 8177, 9912, 1, 1),
 (7913, 7809, '2008/2009', 2, '2008-08-24 00:00:00', 8722, 9810, 1, 1),
 (7914, 7809, '2008/2009', 2, '2008-08-24 00:00:00', 9911, 8721, 2, 2),
 (7915, 7809, '2008/2009', 2, '2008-08-22 00:00:00', 9904, 8398, 0, 0),
 (7916, 7809, '2008/2009', 2, '2008-08-23 00:00:00', 8226, 9788, 1, 0),
 (7917, 7809, '2008/2009', 20, '2009-02-15 00:00:00', 9790, 9912, 2, 0),
 (7918, 7809, '2008/2009', 20, '2009-02-15 00:00:00', 9789, 8398, 1, 1),
 (7919, 7809, '2008/2009', 20, '2009-02-14 00:00:00', 8697, 9788, 1, 1),
 (7920, 7809, '2008/2009', 20, '2009-02-14 00:00:00', 8177, 9823, 2, 1),
 (7921, 7809, '2008/2009', 20, '2009-02-14 00:00:00', 9810, 8721, 0, 2),
 (7922, 7809, '2008/2009', 20, '2009-02-14 00:00:00', 8722, 8295, 0, 0),
 (7923, 7809, '2008/2009', 20, '2009-02-14 00:00:00', 9911, 10189, 2, 1),
 (7924, 7809, '2008/2009', 20, '2009-02-14 00:00:00', 9904, 10269, 3, 3),
 (7925, 7809, '2008/2009', 20, '2009-02-13 00:00:00', 8226, 8178, 1, 4),
 (7926, 7809, '2008/2009', 21, '2009-02-21 00:00:00', 9823, 8722, 1, 2),
 (7927, 7809, '2008/2009', 21, '2009-02-22 00:00:00', 8178, 9790, 1, 2),
 (7928, 7809, '2008/2009', 21, '2009-02-21 00:00:00', 10269, 8226, 3, 3),
 (7929, 7809, '2008/2009', 21, '2009-02-20 00:00:00', 10189, 9789, 1, 1),
 (7930, 7809, '2008/2009', 21, '2009-02-21 00:00:00', 8721, 8177, 2, 1),
 (7931, 7809, '2008/2009', 21, '2009-02-21 00:00:00', 9912, 9911, 1, 1),
 (7932, 7809, '2008/2009', 21, '2009-02-21 00:00:00', 8398, 8697, 2, 1),
 (7933, 7809, '2008/2009', 21, '2009-02-21 00:00:00', 9788, 9904, 3, 2),
 (7934, 7809, '2008/2009', 21, '2009-02-21 00:00:00', 8295, 9810, 0, 1),
 (7935, 7809, '2008/2009', 22, '2009-03-01 00:00:00', 9790, 8721, 1, 3),
 (7936, 7809, '2008/2009', 22, '2009-02-28 00:00:00', 9789, 8226, 0, 0),
 (7937, 7809, '2008/2009', 22, '2009-03-01 00:00:00', 8697, 9823, 0, 0),
 (7938, 7809, '2008/2009', 22, '2009-02-28 00:00:00', 8177, 9788, 2, 1),
 (7939, 7809, '2008/2009', 22, '2009-02-28 00:00:00', 9810, 10189, 1, 2),
 (7940, 7809, '2008/2009', 22, '2009-02-27 00:00:00', 8722, 9912, 1, 1),
 (7941, 7809, '2008/2009', 22, '2009-02-28 00:00:00', 9911, 8398, 3, 2),
 (7942, 7809, '2008/2009', 22, '2009-02-28 00:00:00', 9904, 8178, 1, 0),
 (7943, 7809, '2008/2009', 22, '2009-03-01 00:00:00', 8295, 10269, 0, 2),
 (7944, 7809, '2008/2009', 23, '2009-03-07 00:00:00', 9823, 9904, 5, 1),
 (7945, 7809, '2008/2009', 23, '2009-03-08 00:00:00', 8178, 9911, 1, 1),
 (7946, 7809, '2008/2009', 23, '2009-03-07 00:00:00', 10269, 9789, 2, 1),
 (7947, 7809, '2008/2009', 23, '2009-03-06 00:00:00', 10189, 8722, 1, 0),
 (7948, 7809, '2008/2009', 23, '2009-03-07 00:00:00', 8721, 8295, 1, 0),
 (7949, 7809, '2008/2009', 23, '2009-03-08 00:00:00', 9912, 9810, 0, 0),
 (7950, 7809, '2008/2009', 23, '2009-03-07 00:00:00', 8398, 8177, 1, 3),
 (7951, 7809, '2008/2009', 23, '2009-03-07 00:00:00', 9788, 9790, 4, 1),
 (7952, 7809, '2008/2009', 23, '2009-03-07 00:00:00', 8226, 8697, 0, 0),
 (7953, 7809, '2008/2009', 24, '2009-03-15 00:00:00', 9790, 8398, 2, 0),
 (7954, 7809, '2008/2009', 24, '2009-03-15 00:00:00', 8697, 10269, 4, 0),
 (7955, 7809, '2008/2009', 24, '2009-03-14 00:00:00', 8177, 8178, 1, 0),
 (7956, 7809, '2008/2009', 24, '2009-03-13 00:00:00', 8721, 10189, 4, 3),
 (7957, 7809, '2008/2009', 24, '2009-03-14 00:00:00', 9810, 8226, 1, 1),
 (7958, 7809, '2008/2009', 24, '2009-03-14 00:00:00', 8722, 9788, 2, 4),
 (7959, 7809, '2008/2009', 24, '2009-03-14 00:00:00', 9911, 9823, 0, 3),
 (7960, 7809, '2008/2009', 24, '2009-03-14 00:00:00', 9904, 9789, 4, 4),
 (7961, 7809, '2008/2009', 24, '2009-03-14 00:00:00', 8295, 9912, 0, 1),
 (7962, 7809, '2008/2009', 25, '2009-03-21 00:00:00', 9823, 8295, 1, 0),
 (7963, 7809, '2008/2009', 25, '2009-03-21 00:00:00', 8178, 9810, 1, 1),
 (7964, 7809, '2008/2009', 25, '2009-03-21 00:00:00', 9789, 8697, 1, 0),
 (7965, 7809, '2008/2009', 25, '2009-03-21 00:00:00', 10269, 8177, 2, 0),
 (7966, 7809, '2008/2009', 25, '2009-03-22 00:00:00', 10189, 9790, 1, 2),
 (7967, 7809, '2008/2009', 25, '2009-03-21 00:00:00', 9912, 8721, 0, 3),
 (7968, 7809, '2008/2009', 25, '2009-03-21 00:00:00', 8398, 8722, 0, 2),
 (7969, 7809, '2008/2009', 25, '2009-03-20 00:00:00', 9788, 9911, 0, 1),
 (7970, 7809, '2008/2009', 25, '2009-03-21 00:00:00', 8226, 9904, 2, 2),
 (7971, 7809, '2008/2009', 26, '2009-04-04 00:00:00', 9790, 8226, 1, 0),
 (7972, 7809, '2008/2009', 26, '2009-04-05 00:00:00', 8697, 9904, 4, 1),
 (7973, 7809, '2008/2009', 26, '2009-04-04 00:00:00', 8177, 9789, 1, 3),
 (7974, 7809, '2008/2009', 26, '2009-04-04 00:00:00', 8721, 9823, 5, 1),
 (7975, 7809, '2008/2009', 26, '2009-04-04 00:00:00', 9810, 8398, 2, 1),
 (7976, 7809, '2008/2009', 26, '2009-04-03 00:00:00', 9912, 10189, 0, 2),
 (7977, 7809, '2008/2009', 26, '2009-04-05 00:00:00', 8722, 8178, 0, 2),
 (7978, 7809, '2008/2009', 26, '2009-04-04 00:00:00', 9911, 10269, 1, 2),
 (7979, 7809, '2008/2009', 26, '2009-04-05 00:00:00', 8295, 9788, 0, 0),
 (7980, 7809, '2008/2009', 27, '2009-04-11 00:00:00', 9823, 9810, 4, 0),
 (7981, 7809, '2008/2009', 27, '2009-04-12 00:00:00', 8178, 8697, 1, 1),
 (7982, 7809, '2008/2009', 27, '2009-04-11 00:00:00', 9789, 8722, 3, 1),
 (7983, 7809, '2008/2009', 27, '2009-04-12 00:00:00', 10269, 9790, 1, 0),
 (7984, 7809, '2008/2009', 27, '2009-04-11 00:00:00', 10189, 8295, 2, 0),
 (7985, 7809, '2008/2009', 27, '2009-04-11 00:00:00', 8398, 9912, 2, 1),
 (7986, 7809, '2008/2009', 27, '2009-04-11 00:00:00', 9904, 8177, 2, 0),
 (7987, 7809, '2008/2009', 27, '2009-04-11 00:00:00', 9788, 8721, 1, 2),
 (7988, 7809, '2008/2009', 27, '2009-04-11 00:00:00', 8226, 9911, 0, 3),
 (7989, 7809, '2008/2009', 28, '2009-04-19 00:00:00', 9790, 9904, 2, 1),
 (7990, 7809, '2008/2009', 28, '2009-04-19 00:00:00', 8177, 8697, 2, 1),
 (7991, 7809, '2008/2009', 28, '2009-04-17 00:00:00', 10189, 8398, 4, 0),
 (7992, 7809, '2008/2009', 28, '2009-04-18 00:00:00', 8721, 8178, 2, 1),
 (7993, 7809, '2008/2009', 28, '2009-04-18 00:00:00', 9810, 9788, 4, 1),
 (7994, 7809, '2008/2009', 28, '2009-04-18 00:00:00', 9912, 9823, 0, 1),
 (7995, 7809, '2008/2009', 28, '2009-04-18 00:00:00', 8722, 10269, 0, 3),
 (7996, 7809, '2008/2009', 28, '2009-04-18 00:00:00', 9911, 9789, 0, 2),
 (7997, 7809, '2008/2009', 28, '2009-04-18 00:00:00', 8295, 8226, 2, 2),
 (7998, 7809, '2008/2009', 29, '2009-04-25 00:00:00', 9823, 10189, 0, 1),
 (7999, 7809, '2008/2009', 29, '2009-04-25 00:00:00', 8178, 8295, 0, 1),
 (8000, 7809, '2008/2009', 29, '2009-04-25 00:00:00', 9789, 9790, 2, 0),
 (8001, 7809, '2008/2009', 29, '2009-04-25 00:00:00', 10269, 9810, 2, 0),
 (8002, 7809, '2008/2009', 29, '2009-04-25 00:00:00', 8697, 9911, 3, 2),
 (8003, 7809, '2008/2009', 29, '2009-04-26 00:00:00', 8398, 8721, 2, 0),
 (8004, 7809, '2008/2009', 29, '2009-04-25 00:00:00', 9904, 8722, 2, 1),
 (8005, 7809, '2008/2009', 29, '2009-04-26 00:00:00', 9788, 9912, 1, 1),
 (8006, 7809, '2008/2009', 29, '2009-04-24 00:00:00', 8226, 8177, 0, 1),
 (8007, 7809, '2008/2009', 3, '2008-08-31 00:00:00', 9823, 8177, 4, 1),
 (8008, 7809, '2008/2009', 3, '2008-08-30 00:00:00', 8178, 8226, 5, 2),
 (8009, 7809, '2008/2009', 3, '2008-08-31 00:00:00', 10269, 9904, 2, 0),
 (8010, 7809, '2008/2009', 3, '2008-08-30 00:00:00', 10189, 9911, 1, 0),
 (8011, 7809, '2008/2009', 3, '2008-08-30 00:00:00', 8721, 9810, 2, 2),
 (8012, 7809, '2008/2009', 3, '2008-08-30 00:00:00', 9912, 9790, 2, 4),
 (8013, 7809, '2008/2009', 3, '2008-08-30 00:00:00', 8398, 9789, 0, 1),
 (8014, 7809, '2008/2009', 3, '2008-08-30 00:00:00', 9788, 8697, 3, 2),
 (8015, 7809, '2008/2009', 3, '2008-08-29 00:00:00', 8295, 8722, 0, 2),
 (8016, 7809, '2008/2009', 30, '2009-05-02 00:00:00', 9823, 9788, 2, 1),
 (8017, 7809, '2008/2009', 30, '2009-05-03 00:00:00', 9790, 8177, 1, 1),
 (8018, 7809, '2008/2009', 30, '2009-05-02 00:00:00', 10189, 8178, 1, 2),
 (8019, 7809, '2008/2009', 30, '2009-05-02 00:00:00', 8721, 8226, 4, 0),
 (8020, 7809, '2008/2009', 30, '2009-05-02 00:00:00', 9810, 9789, 0, 2),
 (8021, 7809, '2008/2009', 30, '2009-05-02 00:00:00', 9912, 10269, 2, 2),
 (8022, 7809, '2008/2009', 30, '2009-05-03 00:00:00', 8722, 8697, 1, 0),
 (8023, 7809, '2008/2009', 30, '2009-05-01 00:00:00', 9911, 9904, 0, 2),
 (8024, 7809, '2008/2009', 30, '2009-05-02 00:00:00', 8295, 8398, 0, 0),
 (8025, 7809, '2008/2009', 31, '2009-05-08 00:00:00', 8178, 9912, 2, 2),
 (8026, 7809, '2008/2009', 31, '2009-05-09 00:00:00', 9789, 8295, 4, 0),
 (8027, 7809, '2008/2009', 31, '2009-05-09 00:00:00', 10269, 8721, 4, 1),
 (8028, 7809, '2008/2009', 31, '2009-05-10 00:00:00', 8697, 9790, 2, 0),
 (8029, 7809, '2008/2009', 31, '2009-05-09 00:00:00', 8177, 9911, 2, 0),
 (8030, 7809, '2008/2009', 31, '2009-05-09 00:00:00', 8398, 9823, 1, 3),
 (8031, 7809, '2008/2009', 31, '2009-05-09 00:00:00', 9904, 9810, 1, 1),
 (8032, 7809, '2008/2009', 31, '2009-05-10 00:00:00', 9788, 10189, 1, 0),
 (8033, 7809, '2008/2009', 31, '2009-05-09 00:00:00', 8226, 8722, 2, 0),
 (8034, 7809, '2008/2009', 32, '2009-05-12 00:00:00', 9823, 8178, 3, 0),
 (8035, 7809, '2008/2009', 32, '2009-05-13 00:00:00', 9790, 9911, 3, 1),
 (8036, 7809, '2008/2009', 32, '2009-05-13 00:00:00', 10189, 10269, 1, 2),
 (8037, 7809, '2008/2009', 32, '2009-05-12 00:00:00', 8721, 9789, 3, 0),
 (8038, 7809, '2008/2009', 32, '2009-05-13 00:00:00', 9810, 8697, 0, 5),
 (8039, 7809, '2008/2009', 32, '2009-05-13 00:00:00', 9912, 8226, 0, 2),
 (8040, 7809, '2008/2009', 32, '2009-05-12 00:00:00', 8722, 8177, 1, 2),
 (8041, 7809, '2008/2009', 32, '2009-05-13 00:00:00', 8398, 9788, 0, 1),
 (8042, 7809, '2008/2009', 32, '2009-05-12 00:00:00', 8295, 9904, 2, 3),
 (8043, 7809, '2008/2009', 33, '2009-05-16 00:00:00', 8178, 9788, 5, 0),
 (8044, 7809, '2008/2009', 33, '2009-05-16 00:00:00', 9790, 8722, 0, 1),
 (8045, 7809, '2008/2009', 33, '2009-05-16 00:00:00', 9789, 9912, 6, 0),
 (8046, 7809, '2008/2009', 33, '2009-05-16 00:00:00', 10269, 8398, 2, 0),
 (8047, 7809, '2008/2009', 33, '2009-05-16 00:00:00', 8697, 8295, 1, 3),
 (8048, 7809, '2008/2009', 33, '2009-05-16 00:00:00', 8177, 10189, 0, 0),
 (8049, 7809, '2008/2009', 33, '2009-05-16 00:00:00', 9911, 9810, 2, 0),
 (8050, 7809, '2008/2009', 33, '2009-05-16 00:00:00', 9904, 8721, 0, 5),
 (8051, 7809, '2008/2009', 33, '2009-05-16 00:00:00', 8226, 9823, 2, 2),
 (8052, 7809, '2008/2009', 34, '2009-05-23 00:00:00', 9823, 10269, 2, 1),
 (8053, 7809, '2008/2009', 34, '2009-05-23 00:00:00', 10189, 8226, 2, 3),
 (8054, 7809, '2008/2009', 34, '2009-05-23 00:00:00', 8721, 8697, 5, 1),
 (8055, 7809, '2008/2009', 34, '2009-05-23 00:00:00', 9810, 9790, 2, 3),
 (8056, 7809, '2008/2009', 34, '2009-05-23 00:00:00', 9912, 9904, 2, 2),
 (8057, 7809, '2008/2009', 34, '2009-05-23 00:00:00', 8722, 9911, 1, 1),
 (8058, 7809, '2008/2009', 34, '2009-05-23 00:00:00', 8398, 8178, 3, 0),
 (8059, 7809, '2008/2009', 34, '2009-05-23 00:00:00', 9788, 9789, 1, 1),
 (8060, 7809, '2008/2009', 34, '2009-05-23 00:00:00', 8295, 8177, 4, 0),
 (8061, 7809, '2008/2009', 4, '2008-09-13 00:00:00', 9790, 8178, 3, 2),
 (8062, 7809, '2008/2009', 4, '2008-09-13 00:00:00', 9789, 10189, 3, 3),
 (8063, 7809, '2008/2009', 4, '2008-09-13 00:00:00', 8697, 8398, 3, 0),
 (8064, 7809, '2008/2009', 4, '2008-09-13 00:00:00', 8177, 8721, 2, 2),
 (8065, 7809, '2008/2009', 4, '2008-10-22 00:00:00', 9810, 8295, 2, 1),
 (8066, 7809, '2008/2009', 4, '2008-09-13 00:00:00', 8722, 9823, 0, 3),
 (8067, 7809, '2008/2009', 4, '2008-09-14 00:00:00', 9911, 9912, 2, 0),
 (8068, 7809, '2008/2009', 4, '2008-09-14 00:00:00', 9904, 9788, 5, 1),
 (8069, 7809, '2008/2009', 4, '2008-09-13 00:00:00', 8226, 10269, 0, 0),
 (8070, 7809, '2008/2009', 5, '2008-09-20 00:00:00', 9823, 8697, 2, 5),
 (8071, 7809, '2008/2009', 5, '2008-09-19 00:00:00', 8178, 9904, 4, 0),
 (8072, 7809, '2008/2009', 5, '2008-09-21 00:00:00', 10269, 8295, 3, 1),
 (8073, 7809, '2008/2009', 5, '2008-09-20 00:00:00', 10189, 9810, 1, 0),
 (8074, 7809, '2008/2009', 5, '2008-09-21 00:00:00', 8721, 9790, 3, 0),
 (8075, 7809, '2008/2009', 5, '2008-09-20 00:00:00', 9912, 8722, 2, 0),
 (8076, 7809, '2008/2009', 5, '2008-09-20 00:00:00', 8398, 9911, 1, 1),
 (8077, 7809, '2008/2009', 5, '2008-09-20 00:00:00', 9788, 8177, 0, 1),
 (8078, 7809, '2008/2009', 5, '2008-09-21 00:00:00', 8226, 9789, 4, 1),
 (8079, 7809, '2008/2009', 6, '2008-09-27 00:00:00', 9790, 9788, 1, 0),
 (8080, 7809, '2008/2009', 6, '2008-09-27 00:00:00', 9789, 10269, 3, 0),
 (8081, 7809, '2008/2009', 6, '2008-09-27 00:00:00', 8697, 8226, 5, 4),

In [99]:
%sql DROP VIEW teams_germany; 
%sql CREATE VIEW teams_germany AS SELECT * FROM Team;

   sqlite://
 * sqlite://///home/hamid/python/sql/euro_soccer.sqlite
   sqlite:////home/hamid/python/sql/dataset.sqlite
Done.
   sqlite://
 * sqlite://///home/hamid/python/sql/euro_soccer.sqlite
   sqlite:////home/hamid/python/sql/dataset.sqlite
Done.

[]

# CASE statement

In [104]:
%%sql

SELECT 
	c.name AS country,
    -- Sum the total records in each season where the home team won
	SUM(CASE WHEN m.season = '2012/2013' AND m.home_team_goal > m.away_team_goal 
        THEN 1 ELSE 0 END) AS matches_2012_2013,
	SUM(CASE WHEN m.season = '2013/2014' AND m.home_team_goal > m.away_team_goal 
        THEN 1 ELSE 0 END) AS matches_2013_2014,
	SUM(CASE WHEN m.season = '2014/2015' AND m.home_team_goal > m.away_team_goal 
        THEN 1 ELSE 0 END) AS matches_2014_2015
FROM country AS c
LEFT JOIN match AS m
ON c.id = m.country_id
-- Group by country name alias
GROUP BY country;

   sqlite://
 * sqlite://///home/hamid/python/sql/euro_soccer.sqlite
   sqlite:////home/hamid/python/sql/dataset.sqlite
Done.

[('Belgium', 102, 6, 106),
 ('England', 166, 179, 172),
 ('France', 170, 168, 181),
 ('Germany', 130, 145, 145),
 ('Italy', 177, 181, 152),
 ('Netherlands', 137, 144, 138),
 ('Poland', 97, 110, 114),
 ('Portugal', 103, 108, 137),
 ('Scotland', 89, 102, 102),
 ('Spain', 189, 179, 171),
 ('Switzerland', 84, 82, 76)]

# CASE statement

In [102]:
%%sql

SELECT 
    c.name AS country,
-- Count games from the 2012/2013 season
    COUNT(CASE WHEN m.season = '2012/2013' 
                THEN m.id ELSE NULL END) AS matches_2012_2013
FROM country AS c
LEFT JOIN match AS m
ON c.id = m.country_id
-- Group by country name alias
GROUP BY country;

   sqlite://
 * sqlite://///home/hamid/python/sql/euro_soccer.sqlite
   sqlite:////home/hamid/python/sql/dataset.sqlite
Done.

[('Belgium', 240),
 ('England', 380),
 ('France', 380),
 ('Germany', 306),
 ('Italy', 380),
 ('Netherlands', 306),
 ('Poland', 240),
 ('Portugal', 240),
 ('Scotland', 228),
 ('Spain', 380),
 ('Switzerland', 180)]

In [101]:
%%sql

-- Identify the home team as Bayern Munich, Schalke 04, or neither
SELECT 
    CASE WHEN home_team_api_id = 10189 THEN 'FC Schalke 04'
         WHEN home_team_api_id = 9823 THEN 'FC Bayern Munich'
         ELSE 'Other' END AS home_team,
    COUNT(id) AS total_matches
FROM matches_germany
-- Group by the CASE statement alias
GROUP BY home_team;

   sqlite://
 * sqlite://///home/hamid/python/sql/euro_soccer.sqlite
   sqlite:////home/hamid/python/sql/dataset.sqlite
Done.

[('FC Bayern Munich', 136), ('FC Schalke 04', 136), ('Other', 2176)]

In [32]:
#Improts 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import sqlite3
import matplotlib.pyplot as plt

In [14]:
path = "/home/hamid/python/sql/"  #Insert path here
database = path + 'euro_soccer.sqlite'

In [15]:
conn = sqlite3.connect(database)

In [7]:
conn = sqlite3.connect(database)

tables = pd.read_sql("""SELECT *
                        FROM sqlite_master
                        WHERE type='table';""", conn)
tables

,type,name,tbl_name,rootpage,sql
0,table,sqlite_sequence,sqlite_sequence,4,"CREATE TABLE sqlite_sequence(name,seq)"
1,table,Player_Attributes,Player_Attributes,11,"CREATE TABLE ""Player_Attributes"" (\n\t`id`\tIN..."
2,table,Player,Player,14,CREATE TABLE `Player` (\n\t`id`\tINTEGER PRIMA...
3,table,Match,Match,18,CREATE TABLE `Match` (\n\t`id`\tINTEGER PRIMAR...
4,table,League,League,24,CREATE TABLE `League` (\n\t`id`\tINTEGER PRIMA...
5,table,Country,Country,26,CREATE TABLE `Country` (\n\t`id`\tINTEGER PRIM...
6,table,Team,Team,29,"CREATE TABLE ""Team"" (\n\t`id`\tINTEGER PRIMARY..."
7,table,Team_Attributes,Team_Attributes,2,CREATE TABLE `Team_Attributes` (\n\t`id`\tINTE...

In [23]:
conn = sqlite3.connect(database)

tables = pd.read_sql("""SELECT *
                        FROM Match 
                        JOIN Country ON Match.country_id = Country.id
                        WHERE name = 'Germany'
                        limit 100;""", conn)
tables

,id,country_id,league_id,season,stage,date,match_api_id,home_team_api_id,away_team_api_id,home_team_goal,...,VCD,VCA,GBH,GBD,GBA,BSH,BSD,BSA,id,name
0,7809,7809,7809,2008/2009,1,2008-08-15 00:00:00,499317,9823,9790,2,...,3.50,5.50,1.60,3.60,5.75,1.53,3.75,5.50,7809,Germany
1,7810,7809,7809,2008/2009,1,2008-08-16 00:00:00,499318,8178,9789,2,...,3.25,3.25,2.05,3.30,3.50,2.00,3.25,3.40,7809,Germany
2,7811,7809,7809,2008/2009,1,2008-08-16 00:00:00,499319,10189,9904,3,...,3.60,6.00,1.60,3.60,5.60,1.57,3.75,5.00,7809,Germany
3,7812,7809,7809,2008/2009,1,2008-08-16 00:00:00,499320,8721,8722,2,...,3.40,5.00,1.63,3.60,5.50,1.57,3.75,5.00,7809,Germany
4,7813,7809,7809,2008/2009,1,2008-08-17 00:00:00,499321,9810,8177,0,...,3.25,2.90,2.35,3.15,3.00,2.25,3.25,2.88,7809,Germany
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,7904,7809,7809,2008/2009,19,2009-02-06 00:00:00,499484,9912,8177,1,...,3.30,2.50,2.60,3.25,2.60,2.50,3.25,2.62,7809,Germany
96,7905,7809,7809,2008/2009,19,2009-02-08 00:00:00,499485,8398,9904,3,...,3.30,2.50,2.63,3.25,2.63,2.50,3.25,2.62,7809,Germany
97,7906,7809,7809,2008/2009,19,2009-02-07 00:00:00,499486,9788,8226,1,...,3.40,2.10,3.40,3.30,2.10,3.40,3.30,2.05,7809,Germany
98,7907,7809,7809,2008/2009,19,2009-02-07 00:00:00,499487,8295,9790,3,...,3.30,1.90,4.00,3.25,1.95,4.00,3.25,1.91,7809,Germany
99,7908,7809,7809,2008/2009,2,2008-08-23 00:00:00,499326,9790,8295,2,...,4.00,7.00,1.45,4.00,7.00,1.44,4.00,6.50,7809,Germany

In [12]:
conn = sqlite3.connect(database)

tables = pd.read_sql("""SELECT *
                        FROM Team
                        limit 5 ;""", conn)
tables

   id  team_api_id  team_fifa_api_id     team_long_name team_short_name
0   1         9987               673           KRC Genk             GEN
1   2         9993               675       Beerschot AC             BAC
2   3        10000             15005   SV Zulte-Waregem             ZUL
3   4         9994              2007   Sporting Lokeren             LOK
4   5         9984              1750  KSV Cercle Brugge             CEB

In [30]:
%%sql

select * 
From users;

   sqlite://
 * sqlite://///home/hamid/python/sql/euro_soccer.sqlite
   sqlite:////home/hamid/python/sql/dataset.sqlite
(sqlite3.OperationalError) no such table: users
[SQL: select * From users;]
(Background on this error at: http://sqlalche.me/e/e3q8)